# Generated by Django 3.2.13 on 2023-06-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
