# Generated by Django 3.2.13 on 2023-06-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
    ]
