# Generated by Django 3.2.13 on 2023-06-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230627_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_tags',
        ),
    ]
